### ISSUE TITLE
Support for typings

### ISSUE THREAD

**Issue by jbcazaux** [Esri/Terraformer#276]
Would be so great to have *.d.ts files.

**Comment by JeffJacobson** [comment]
I created some [TypeScript definition files for Terraformer](https://github.com/WSDOT-GIS/terraformer-typescript-defs/), but they are untested. @jbcazaux, if you (or anyone else) have time to create tests, [feel free to contribute](https://github.com/WSDOT-GIS/terraformer-typescript-defs/issues/1).

If @Esri is OK with it, I could make a pull request and add these `.d.ts` files directly to the appropriate Terraformer* repositories. Otherwise I could [contribute them to the typings repository](https://github.com/typings/registry#contributing).

**Comment by jgravois** [comment]
> I could make a pull request and add these .d.ts files directly to the appropriate Terraformer* repositories

i'd **definitely** be interested in that.  it will give me an excuse to get familiar with TypeScript.

**Comment by jbcazaux** [comment]
Thank you so much, i'm gonna give it a try.

**Comment by jgravois** [comment]
TypeScript typings have been included in [`1.0.6`](https://github.com/Esri/Terraformer/releases/tag/v1.0.6).

thx @JeffJacobson 🎉
