### ISSUE TITLE
http://terraformer.io site is down

### ISSUE THREAD

**Issue by adamajm** [Esri/terraformer#348]

**Comment by jgravois** [comment]
yup. we let the domain expire. see https://github.com/Esri/terraformer/issues/319

**Comment by jf990** [comment]
actually, did someone just move it to a new domain and not say anything? https://terraformer-js.github.io/

**Comment by jgravois** [comment]
hey @jf990.
see https://github.com/Esri/terraformer/issues/319#issuecomment-565163390

**Comment by jgravois** [comment]
yup. when the domain was set to expire in 2019, we renewed it one more time and set up the redirect. now, googling 'terraformer js' advertises the new page (https://terraformer-js.github.io/).

Esri has _heaps_ of links to http://terraformer.io scattered across the internet though. its entirely up to y'all, but if i were in your position i would prefer to spend $30/year and keep control of the domain. otherwise folks are going to start seeing whatever page a squatter puts up in its place very soon.

**Comment by jf990** [comment]
Thanks @jgravois -- I'm working on it ...

**Comment by adamajm** [comment]
@jf990 any news here?

**Comment by jgravois** [comment]
a squatter has taken hold of the domain, so unfortunately now it's a moot point.

**Comment by jf990** [comment]
@adamajm @jgravois I was working on it a month a ago and the domain was reclaimed. i don't know what we can do about it now. sorry, I couldn't get action from the appropriate forces on this side.
